### ISSUE TITLE
Make 7z a must for uploading (for time and bandwidth saving)

### ISSUE THREAD

**Issue by necros2k7** [itchio/itch.io#1014]
subj

**Comment by fasterthanlime** [comment]
That doesn't seem like a good move for us at this time.

The recommended way to upload is https://itch.io/docs/butler/ - which uses brotli compression on upload, and only upload changes.

The benefits (and comparisons with other strategies) are outlined in https://itch.io/docs/itch/integrating/compatibility-policy.html

7z offers "pretty good" compression, but: doing it on the developer's machine before upload wastes time, it's not a good canonical archive format because it doesn't provide random access, and even the most basic 7z unpacker involves a lot of code.

I'm happy with our current strategy, although I wish more folks used butler, and I always have improvements in mind for it.
