### ISSUE TITLE
Automatically start on page load" on mobile browsers not working

### ISSUE THREAD

**Issue by MohammadKhashashneh** [itchio/itch.io#1046]
I already asked this on the questions & support forum, https://itch.io/t/683089/automatically-start-on-page-load-on-mobile-browsers#post-1183620
but had no answers, so I'm opening an issue here. 
----------------------------------------------------------------------------------------------------------------
I have an HTML5 project and would like it to start loading/playing when users first visit the project page.
While the "Automatically start on page load" option is working fine on PC browsers it's not for mobile browsers and requires the user to press the "Run Project" button instead! is there something I'm missing?

**Comment by MohammadKhashashneh** [comment]
A link to test:
https://mohammad-rasmi.itch.io/tcm?secret=m0FHcT8F8rVxMZwEYUqpfLWrXw

**Comment by leafo** [comment]
Sorry I haven't responded sooner. We intentionally do not make this part of how HTML5 games are embedded on mobile. Our mobile runner for HTML5 games always makes the game fullscreen since viewport size is limited, and we don't want people trying to play a game with it scrolling around. Since all games run on fullscreen, we can not start the game immediately since we need to initially show the user the page. Additionally, they can decide whether or not they want to start the project since many html5 games can have high resource & bandwidth costs. Hope that explains.
