### ISSUE TITLE
[A11Y]  Not possible to rate games using a "screen Reader"

### ISSUE THREAD

**Issue by Superfreq2** [itchio/itch.io#1094]
As a blind user I am not able to rate games which I have purchased on the site.  Most of itch.io is accessible with screen reading software, but this is one of the major problem areas.
I would really like to show my support and give recognition with a good rating for the developers I follow, many of whom have done allot of good work to make their games more accessible for people with disabilities.
I have tested with both Firefox and Chrome, and with the three most widely used Screen Readers for Windows. In all cases, the review text box works fine, but the place where you presumably choose your rating does not speak at all and does not even appear as a usable element to me.

**Comment by pitermach** [comment]
+1. Ratings are really important and it's incredibly frustrating that I can't do this independently, especially considering that itch.io is home to a number of developers who pay close attention to accessibility, both for people with blindness as well as other disabilities. I just tried to leave a rating for a game and here's a couple more detailed findings:

- When the rating dialog pops up, it doesn't automatically gain focus. This means that unless you know you need to move the screen reader cursor to the bottom of the page and look for it, you won't know that it's there. Additionally, that entire popup should probably get the aria dialog role, which combined with a control gaining focus would cause screen readers to give an appropriate announcement.
- The close button to close the dialog without leaving a rating, while visible with a screen reader and focusable by tabbing, doesn't have a textual label which results in screen readers just saying the word "button" without any context.
- The rating widget itself is broken in multiple ways. It has no keyboard support at all, so if you tab through the page into the dialog, you'll come across the close button, then after tabbing the focus will skip the rating widget and go straight to the text review editor. If you read through the page with a screen reader, the entire widget will simply appear as a single element announced simply as "clickable", because from what I gathered by looking through the page dom it's just a bunch of span elements reacting to mouse clicks. The best way to represent this to a screen reader would probably be as a group of radio buttons, because on a rating control you can generally have only 1 thing selected.
- On a more positive note at the end, the widget you're using to write the text portion of the review has excellent accessibility support, which allows you to even insert formatting in a very pleasant way, so nothing needs to be done there. The save button is also OK, with a clear label and being reachable with tab.

Here is an [example of making an accessible star control](https://www.w3.org/WAI/tutorials/forms/custom-controls/#a-star-rating) which fits this use case really well which also recommends the radio button approach, though you probably won't need to do the submit button part as this article suggests as you actually need to press save to send the review form. The rest would work really well here though. It's also worth noting that implementing these or similar changes in the future won't just improve blindness accessibility, as people relying on other assistive technologies like switch access or voice recognition would also benefit from controls reachable by the keyboard or having clear labels

**Comment by leafo** [comment]
Thanks for the feedback. There are actually two rating & review on the site at the moment, and the one accessed via the game page has not been migrated yet. You can access the updated one on https://itch.io/library/things-to-rate which should have a more accessible star rating picker.

**Comment by pitermach** [comment]
Thanks for a prompt response, I'm glad to see this is/was already worked on! :) That other dialog is indeed much better and I just caught up on all of the games I wanted to rate.

One really minor thing about the new dialog, if possible, it would be nice if there could be an indication as to which rating is selected, IE if the label changed to also say selected or something to that effect, this way if I want to write a review, get distracted and step away and then come back I could see what rating I selected in-case I forgot. For now you can just press the button again if you're unsure, so it's not too big of a problem but it's something probably worth fixing since the rest of the interface works really well. :)

**Comment by leafo** [comment]
> One really minor thing about the new dialog, if possible, it would be nice if there could be an indication as to which rating is selected

Thanks for the suggestion, I made it include "Selected" in the label.

**Comment by pitermach** [comment]
Wow that was fast! I see this is already live, thanks again. I think this is pretty much perfect now. :)

**Comment by devinprater** [comment]
Thanks so much for correcting this so quickly. I've not used itch.io yet, but I am a blind gamer so I'll definitely support such great accessibility response.

**Comment by leafo** [comment]
Hey everyone, sorry for taking a while to fully address this but I just pushed out an update that fully migrates the rating dialog to the more accessible new one. This also includes a basic focus trap + focus restoring along with the updates to the star rating picker that were introduced in #1109.

Tell me if you spot any issues and I'd be glad to fix them. This most recent update also gets us started on modernizing the rest of our dialogs so they can be more accessible.

**Comment by Superfreq2** [comment]
Fantastic!  Thank you for your work and for the commitment to #A11Y
