### ISSUE TITLE
Itch app not working

### ISSUE THREAD

**Issue by sup3r10rx** [itchio/itch.io#1122]
so i share this laptop (we have separate accounts on the laptop) and i cant access the itch app through shortcuts i havve to run the installer everytime i want to use it.  I am not an administrator on the pc so that may be the issue but it may also be that i update windows and it auto deleted itch.  the weird thing though is before it updated itch worked fine. also i re installed the games and some didn't work

**Comment by leafo** [comment]
I'm going to close this because we can't really offer specific solutions for issues with your computer's configuration. It sounds like the policies on you computer are potentially breaking the app. You can always try deleting the app data directory entirely and reinstalling to see if that helps.

(Also this is the wrong rep, app one here: https://github.com/itchio/itch/issues )
