### ISSUE TITLE
Itch and paypal lost my payout

### ISSUE THREAD

**Issue by tibbius** [itchio/itch.io#1164]
Itch payout screen says I received a payout to my paypal address yesterday. But the invoice says no payment was made. Paypal does not record funds received.

Where is my money?

**Comment by leafo** [comment]
Did you send in a support ticket? We typically only process private account information through our support system, and not through a public issues tracker. This error is typically because you have your payout destination set incorrectly for PayPal. Please reply with a ticket ID after your receive it from [contacting us through our support system](https://itch.io/support).

**Comment by tibbius** [comment]
The payout page reports that the payout was sent to my usual paypal address. But it never showed up!
- Tibbiushttps://tibbiusgames.itch.io/ 

    On Wednesday, February 24, 2021, 02:54:53 PM EST, leaf <notifications@github.com> wrote:  
 
 


Did you send in a support ticket? We typically only process private account information through our support system, and not through a public issues tracker. This error is typically because you have your payout destination set incorrectly for PayPal. Please reply with a ticket ID after your receive it from contacting us through our support system.

**Comment by leafo** [comment]
Closing this since we followed up on the support ticket.
