### ISSUE TITLE
I want to delete my account.

### ISSUE THREAD

**Issue by McLovin-Foggle** [itchio/itch.io#1326]

**Comment by McLovin-Foggle** [comment]
How do I do it?

**Comment by librafrog** [comment]
According to Itch docs quote: Users can terminate their account at any time, but are not entitled to a refund because of such termination.…You may cease to use your account, or if you so choose, may request that the Company terminate your access to your account. User accounts may not be transferred, sold, or assigned to a third party, and such actions may result in account termination. User account termination does not entitle the user to a refund. Didn't find an account option so write to [support](https://itch.io/support)
![](https://img.shields.io/badge/itch-docs-important?logo=itchdotio)

**Comment by leafo** [comment]
We don't do account support on the GitHub issues tracker.

If you contact support from here https://itch.io/support using the email address that owns the account you can request it to be deleted.
