### ISSUE TITLE
PROBLEM: ITCH.IO-HOSTED HTML5 Games do NOT anymore execute ERROR

### ISSUE THREAD

**Issue by masarapmabuhay** [itchio/itch.io#1404]
Hallo,

**PROBLEM:** 

ITCH.IO-HOSTED HTML5 Games do NOT anymore execute ERROR

observed: "...ssl.hwcdn.net" notification after pressing "Run game" button @20230105T2000 (Philippine TIME);

verified: with the following GAME OFF 2022 Entries via web browser (Mozilla Firefox):

https://badcop.itch.io/graveyard-shift
https://mikanhako.itch.io/stay-power
https://almamu.itch.io/a-bird-in-hand-is-worth-hundreds-in-the-bush

notes: the following entry had previously executed on web browser (Mozilla Firefox):

https://dorfs.itch.io/a-kings-ransom

Thank you.

Health,
SYSON, MICHAEL B.

**Comment by EasternMouse** [comment]
First one can't be played because it uses Shared Array Buffer (checked source code they had) which is not currently working on Firefox (for 200 days already) [https://itch.io/t/2025776/experimental-sharedarraybuffer-support](https://itch.io/t/2025776/experimental-sharedarraybuffer-support). Can assume other entries are same, if they work on Chrome but not FF.

Only thing sensible for now I guess is devs should try to stay away from this feature or warn that game can't be played on Firefox, other than that - just wait until Firefox starts working with feature.

**Comment by masarapmabuhay** [comment]
Hallo,
Thank you for sharing your feedback.

I remember receiving "Shared Array Buffer" ERROR notification when attempting to execute HTML5 apps that use the feature.

The first one, 
https://badcop.itch.io/graveyard-shift, didn't appear to have that ERROR notification, albeit I did remember NOT being able to execute it even previously.

Health,
SYSON, MICHAEL B.

**Comment by EasternMouse** [comment]
Oh, yeah, seems to be second is Unity/C#, not seeing source for 3rd - probably too.

My game where I just recently encountered this problem is made in Godot, same as first game in list, I guess Unity throws error, while Godot tries to load anyway and gets stuck in infinite loop.

**Comment by masarapmabuhay** [comment]
Hallo, 

It appeared to me that there may have been an update in ITCH.IO that caused the ERROR. This was after verifying that even this GAME that previously executed on FIREFOX didn’t anymore.

https://dorfs.itch.io/a-kings-ransom

But if there were people who were reviewing and rating https://badcop.itch.io/graveyard-shift, and without noticeable feedback on the ERROR, FIREFOX may not really be the browser of choice used by most people at GAME OFF. 

I understand that you use FIREFOX due to you have encountered the ERROR. I have preferred to use FIREFOX over CHROME or SAFARI, because I’ve been using MOZILLA APACHE tools as a developer. EDGE appears to be the next that I use, after a FIREFOX update caused the browser to not anymore execute on my recycled Windows machine.

Health,
SYSON, MICHAEL B.

**Comment by leafo** [comment]
We have not made any changes to our HTML embed system in some time. 

As a developer you can control some of the headers associated with your HTML file as described here: https://itch.io/t/2025776/experimental-sharedarraybuffer-support

This option toggles between two CDN configurations, one with strict CORS headers and one without. In order to utilize things like SharedArrayBuffer you must be using the more strict configuration (aka itch.zone). The legacy domain represents an iframe with no cross-site headers. (v6p9d9t4.ssl.hwcdn.net)

**Comment by masarapmabuhay** [comment]
Hallo, leafo,

Thank you for the reply.

OK! IF the developers also did NOT make any changes in their uploaded HTML app, then the ERROR may have been due to an update in the FIREFOX BROWSER.

I shall now close this incident report unless anyone disagrees.

The CURRENT SOLUTION for USERS would be to verify with another web browser, e.g. EDGE, CHROME, SAFARI.

Thank you.

Health,
SYSON, MICHAEL B.

**Comment by masarapmabuhay** [comment]
Hallo,

Thank you for the update notification.

I re-verified the following GAME @20230212T05:42~05:53 (PHILIPPINE TIME):
https://badcop.itch.io/graveyard-shift

OUTPUT#1 (using macOS):
1) FIREFOX (v109.0.1 64-bit)
—> can load game until TITLE/MENU SCREEN;
—> SETTINGS, CREDITS SCREENS appear functional;
—> pressing PLAY button causes BLANK SCREEN;
—> observed: SOUND continues;
—> notes: SOUND continues for < 10secs, even after closing FIREFOX ;

2) SAFARI (v12.1.2 12607.3.10)
—> continues loading only

3) GOOGLE CHROME (v103.0.5060.134 (Official Build) (x86_64))
—> received: notification to upgrade macOS to 10.13; currently @10.12

OUTPUT#2 (using Windows 7 Ultimate OS):
1) EDGE
—> “html.itch.zone” isn’t responding;

I hope this test results report is also useful for you and your team.

Health,
SYSON, MICHAEL B.
