### ISSUE TITLE
Game Jam not visible even though it's published

### ISSUE THREAD

**Issue by mariosbikos** [itchio/itch.io#1487]
Hi there!
We recently started an [itch.io](http://itch.io/) game jam page for PICO Dev Jam 2023: https://itch.io/jam/2023-pico-dev-jam

However, it is not visible in the game jams calendar and when we search for it, we can't find it even though it's set to published.

Can you help us make it indeed public and searchable?

**Comment by leafo** [comment]
To prevent spamming, accounts that are new to hosting jams must have their jam pages reviewed before they are eligible to appear in the calendar. The page is otherwise fully functional, and you should promote the page as normal. In fact, getting your community to join can help it get reviewed faster.

I can confirm your page is now reviewed and eligible for indexing in our jam calendar.
