### ISSUE TITLE
Longer character limit for the "Custom noun" field.

### ISSUE THREAD

**Issue by PolybiusMaximus** [itchio/itch.io#1553]
I am creating a "project management tool" which is 23 characters, one above the 22 character limit.

Perhaps 32 characters would be better.

**Comment by leafo** [comment]
We limit the length of this field so that it can appear in various parts of the UI without causing wrapping issues. It was already expanded once beyond the ideal length so we won't be increasing it further at this time. I recommend finding a different noun or phrase to represent your project, or use the default!
