### ISSUE TITLE
There is no way to add a game to a collection on mobile

### ISSUE THREAD

**Issue by hach-que** [itchio/itch.io#156]
There is currently no way to add a game to a collection on mobile. This seems like one of the most useful areas for collections, for example I have a collection entitled "games to play later", which I use to store interesting games. However if I stumble upon or am linked a game while on mobile, I have to use Pushbullet to send the URL to my computer so I can add it to a collection later.

**Comment by Xananax** [comment]
Same here. I know about games through twitter/reddit/chat. In other words, I learn about, and catalogue games, on my mobile. I play, however, on my desktop. In other words, the mobile version of itch is, for me, only used to add games to catalogues. It's just annoying because of the workarounds needed.

I'd argue that not many people browse on mobile? They land on a page, check the game, and then, since you can't add it to a catalogue, can't play most of the times, and can't download, just fail to have a call to action and close the tab. That'd be my assumption any way.

If I'm right (you guys have the numbers to know) I'd argue you can ditch everything else, and focus the mobile version about reminding users of what interested them when they were in the loo. "remind me with an email later", "add the link to my notes" or whatever other integrations you can think of.

**Comment by nanodeath** [comment]
The browse-and-add-to-collection experience on mobile is pretty terrible. You essentially only have one option that works: when browsing through various items, if you want more details on an item, you *must* long-press and open that item in a new tab, and if you like it, go back to your main tab and choose "Add to collection". The usual "click on it, see if I like it, add it to a collection if I do, go back" workflow is completely broken on mobile.

This is because two things: 1. there's no way to add a game or assets to a collection on mobile, and 2. when you go *back* to a search result page on mobile, because it's all "infinite scroll"-ified, it you lose your place. That second issue is a separate issue, but...I'd still love to see better "Add to collection" support on mobile.
