### ISSUE TITLE
Itch.io downloading 

### ISSUE THREAD

**Issue by Pxlskx** [itchio/itch.io#1611]
Hi everyone. I have encountered an error (HTTP 403), downloading "Doge: to the Moon!" by Zacitus, and I don't know how to solve this problem.
Can you help me anyway with downloading this game?
P.s. other games install without any errors, just immediately after clicking button "install".
For extra experience, you can try to download this game(https://zacitus.itch.io/doge-to-the-moon) too, and if you have the same error, please let me know about it.
Thanks.
![IMG_20240618_020544](https://github.com/itchio/itch.io/assets/173111032/acfe8fc8-5e84-4f57-8c56-2fd355e91520)
![IMG_20240618_020531](https://github.com/itchio/itch.io/assets/173111032/b3cc6282-158a-4dee-b505-e4ade6566795)

**Comment by CosmoMyzrailGorynych** [comment]
This is replicatable and seems to affect this particular project. Other projects with same download process (with "no payments" mode) work. Wild guess: this might be because the filename contains a `!` sign.

When requesting this: (some probably sensitive parts were replaced with ✨)
`https://itchio-mirror.cb031a832f44726753d6267436f3b414.r2.cloudflarestorage.com/upload/9980/Doge%2B-%2BTo%2Bthe%2BMoon!.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=✨/20240619/auto/s3/aws4_request&X-Amz-Date=20240619T133211Z&X-Amz-Expires=60&X-Amz-SignedHeaders=host&X-Amz-Signature=✨`

a 403 response is returned:
`<?xml version="1.0" encoding="UTF-8"?><Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your secret access key and signing method. </Message></Error>`

**Comment by Pxlskx** [comment]
So, is it fixable problem or not ?

**Comment by Pxlskx** [comment]
> This is replicatable and seems to affect this particular project. Other projects with same download process (with "no payments" mode) work. Wild guess: this might be because the filename contains a `!` sign.
> 
> When requesting this: (some probably sensitive parts were replaced with ✨) `https://itchio-mirror.cb031a832f44726753d6267436f3b414.r2.cloudflarestorage.com/upload/9980/Doge%2B-%2BTo%2Bthe%2BMoon!.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=✨/20240619/auto/s3/aws4_request&X-Amz-Date=20240619T133211Z&X-Amz-Expires=60&X-Amz-SignedHeaders=host&X-Amz-Signature=✨`
> 
> a 403 response is returned: `<?xml version="1.0" encoding="UTF-8"?><Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your secret access key and signing method. </Message></Error>`
So, is it fixable problem or not ?
