### ISSUE TITLE
Game Page

### ISSUE THREAD

**Issue by Re1sei** [itchio/itch.io#1630]
Hello, I posted the game I had it in New and Popular and Latest. After I posted an update and changed the game page a bit, it is from there I have no longer there at all. What could be the problem ? It's checked to public. I only changed the cover, reloaded the game files to new ones, and changed the name of the version. Also added a devlog about the new update.
Game Page - https://hotgamedev.itch.io/fierypassions

**Comment by leafo** [comment]
This place is for bug reports or feature requests, not for customer support or account issues with regards to our content review system. If a page is flagged for human review then you will have to wait for that to take place before your page is eligible for indexing.

https://itch.io/docs/creators/getting-indexed

Also, if you have to post a bug report please use a meaningful subject so that others can understand the issue at a glance. "Game Page" is not that.

Thanks
