### ISSUE TITLE
Better 'already-claimed key' flow

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch.io#167]
The current behavior for keys that are already claimed is confusing to users not yet savvy with how itch.io works.

Original suggestions:

> I just got an invalid key for System Recovery from Groupees, and I've
> reached out to them to fix it, but that isn't what my message is about.
> When I paste the key in (`redacted url`), it redirects to the main store page for the game (`redacted url`). If I wasn't already familiar with the itch.io experience, I wouldn't even realize something had gone
> wrong (since I know there is supposed to be a screen asking to link it to my account). Perhaps you should have a splash screen (before continuing to auto-redirect) that warns users that the key was invalid?

And:

> A friend tried to redeem an itch.io key for a game from one of the Groupees bundles, but it just redirected him to the game page instead without any message. He's contacted Groupees about a replacement, but it might be handy for some message to pop up saying that the key is invalid or used already on itch.io itself, rather than a redirection.

**Comment by criptych** [comment]
Possibly related:  I tried to redeem a key link when I wasn't yet logged in to itch.io, and after logging in, was redirected to my library page instead of back to the redeem page.  The game was not in my library, and going back to try and redeem it again, I get the message that "This download page is owned by another account on itch.io."  The link was sent to me privately (via Kickstarter), not from a public "throwaway" post, so I'd think the odds are low of someone else brute-forcing the key in the short time since I got it.

**Comment by leafo** [comment]
@criptych are you sure it wasn't already connected to another account? This is our GitHub issues tracker and not customer support, so we can't really do much here. If you want to contact us from here https://itch.io/support with details, including the claim URL, and reply to me with the ticket ID I can look into it.

Also closing this outdated ticket

**Comment by criptych** [comment]
> @criptych are you sure it wasn't already connected to another account? 

Pretty sure, since it was only sent in the last month or so (I'm bad about checking my email). It's possible someone used it, but it wasn't me, and that would be a whole other problem. 

I tried to find out if anyone else had this happen, and came across this issue that sounded very similar and was still open, so I thought maybe it was an unresolved bug. I'll contact support and (if necessary) open a new issue.
