### ISSUE TITLE
Problems with payment

### ISSUE THREAD

**Issue by vagalume111** [itchio/itch.io#364]
I tried to pay for Digital Homicide Bundle with my credit card, but the site said the card was declined. However, the credit card sent me two sms saying the payment was approved, what means I was billed for that, and I was billed twice!! I'd be glad if you could solve this problem

**Comment by leafo** [comment]
Hello,

Please use our support email for any payment issues so you don't have to worry about sharing any private information publicly: https://itch.io/support

In the past we've seen test transactions be done by the credit card provider when trying to verify a purchase. If it was not credited on itch.io then it will be refunded to you within the next day or so. If not, you'll need to file a support request with your credit card provider, since we don't have access to the funds.
