### ISSUE TITLE
Dashboard - Activity Summary

### ISSUE THREAD

**Issue by matriax** [itchio/itch.io#401]
I get some high activity of views/downloads but i don't know in what game/stuff was, so i just clicked 1x1 to see which one to know why, maybe some web put my link, article or something, or a RT on twitter,etc...

Maybe doing something like this to see fast how well are doing each one:
![activity_summary](https://cloud.githubusercontent.com/assets/16635665/14735837/9d72569a-0873-11e6-8f8b-8f67d9fde670.png)

Is a fast sketch but i guess you get the point ;)

**Comment by felixplesoianu** [comment]
I agree. The aggregate view isn't very useful in its current form. On the dashboard, I'd like to see *which* projects got the most views on any given day. A simple sum isn't very useful because I advertise each product differently, to different audiences, at different times. It's apples and oranges.

Of course, it's not that hard going through 8 products manually to see which one got visits recently, so this is firmly in "nice to have" territory. But if I had 16 of them, it could easily get uncomfortable. YMMV.

**Comment by fasterthanlime** [comment]
That's our thursday #itchioweek feature! http://blog.itch.io/post/144257242519/itchio-week-day-4-dashboard
