### ISSUE TITLE
Add HTTPS to blog.itch.io

### ISSUE THREAD

**Issue by ekaris** [itchio/itch.io#425]
Add HTTPS to blog.itch.io

**Comment by fasterthanlime** [comment]
original discussion: https://github.com/itchio/itch/issues/638

**Comment by leafo** [comment]
Tumblr doesn't allow https on custom domains :(

**Comment by fasterthanlime** [comment]
@leafo I linked the original discussion b/c Cloudflare might save us there (found an article of theirs that suggested doing it)

**Comment by ekaris** [comment]
They have a free plan with free HTTPS

**Comment by leafo** [comment]
Doesn't work with tumblr

https://support.cloudflare.com/hc/en-us/articles/200168566-How-do-I-add-a-Tumblr-custom-domain-

**Comment by fasterthanlime** [comment]
Ah, must've found an out-of-date article then :(

**Comment by ekaris** [comment]
Why close? There are alternatives, wordpress, google blog, and I think other CDN have HTTPS for free

**Comment by fasterthanlime** [comment]
> Why close?

Maybe @leafo will disagree with me here, but:

  * We're not planning to move off Tumblr anytime soon (part of or our community is there, etc.) - we do have our own blog platform, but it's unfinished (and already supports HTTPS - https://itch.io/blog/3/developer-interview-with-ditto)
  * As such, this issue is not immediately actionable - it's useful that is't there (even closed), but HTTPS is just one of the good practices we care about - we don't have an issue open that says "Don't screw your users", it's just common sense.

I don't think not having HTTPS on the blog is a security issue for the rest of the site (maybe I'm wrong?), so the potential resolutions I see are 1) Tumblr fixing 'HTTPS using an external CDN' support (Cloudflare isn't at fault here, afaict), or 2) our Tumblr blog becoming archives (still in plain http) and our custom-made blog becoming the main one. I'd rather have 2), but we'd need to finish our blogging platform for that.

Hopefully that clears things up! I'm usually quick to open, close & re-open issues, and none of it means I don't care about user feedback and/or security. But, again, @leafo may have a different opinion.

**Comment by leafo** [comment]
I'd like to stay on Tumblr for the time being. We have a decent following there so it's a good place for us to announce updates. itch.io's session cookie is https only so it isn't transmitted on the insecure blog.itch.io connection.
