### ISSUE TITLE
Contact author form

### ISSUE THREAD

**Issue by hryx** [itchio/itch.io#47]
A contact form for reaching the game creator would be useful for sending feedback, bug reports, support questions, and pre-purchase inquiries. I've already had a couple cases where I wanted to write to an author because their game wouldn't run as expected.

As is my typical excuse, Bandcamp has this feature too, but it seems particularly apt when software is involved.

**Comment by aaronfranke** [comment]
If the author wanted to be contacted, wouldn't they provide contact information on their user page?

**Comment by Guard13007** [comment]
@aaronfranke Yes, but there is a different level of convienence from "here's an email address, go open your email client / email webpage and copy-paste it, then write some stuff" (or even a mailto: link) and a form that just handles that for you.

Especially if, say, a dev doesn't like email and itch.io develops some sort of internal tracking thing for this.. Which I'm not suggesting for the record, I think just a simple optional email form should be sufficient.

I vote for this idea, but opt-in of course, because I'm sure there are devs who would hate it. I don't remember if itch.io publicly uses account emails anywhere (I don't think it does), hence why I would want to say this should be opt-in. (Even if this doesn't expose the email, it still will be inviting email to your inbox.)

**Comment by aaronfranke** [comment]
My only point is that I don't see a practical difference between a form and just providing an E-mail address. 

* If it's opt-in, developers have to specifically enable it, just as developers would have to post an E-mail address. I don't see a problem with using E-mail to contact people. In fact, one disadvantage of a web form versus an E-mail is that most E-mail services will auto-save, but web forms do not.

* Alternatively, if it's opt-out, some developers may not even check this Itch mail.

One idea I had is that Itch could provide some kind of forwarding service, to keep the users' E-mail addresses a secret. Users could send an E-mail to blahblah1234@itch.io, Itch.io sends it to developer-email@gmail.com, developers reply to blahblah1234@itch.io, Itch sends it back to user-email@gmail.com.

**Comment by Guard13007** [comment]
The practical difference is convenience, that's all.

**Comment by hryx** [comment]
Good points about providing contact info when you want to. Don't want to add new potential for abuse anyway.

**Comment by RokeJulianLockhart** [comment]
@hryx, [`itch.io/post/6113385`](https://itch.io/post/6113385) might be useful, if true.
