### ISSUE TITLE
Feature: Allow someone to own a game they downloaded for free

### ISSUE THREAD

**Issue by Guard13007** [itchio/itch.io#508]
As mentioned in #507 it would be nice to have the option to allow someone to own a game downloaded for free, either during a 100% off sale, or when a game is free and later costs money.

**Comment by ssokolow** [comment]
I think this would also benefit developers since the current situation suffers from the intersection of two situations:

1. We instinctively value free less than paid. 
2. When we're already spoiled for choice, it's harder to interest us in new things.
3. With the "ownership" aspect taken out of the equation, the game gets filed into the same mental "there's no rush" bin as pirate torrents and the promotional "forever... until we're under new management" freeware releases of games like C&C Gold and GTA2.

If nothing else, allowing ownership means that people who are glutted for choice will click the "Buy at 100% off" button now because it *feels* like a limited time offer with substance, and then have it staring at them from their collection until, maybe, years later, there will be a gap in the more "appealing at first sight" releases in the genre and they'll try it.

(There's a reason I have thousands of paid downloads but almost no free ones.)

**Comment by leafo** [comment]
The one hesitation from me is that sometimes developers put up a free game, then later decide to make a paid version. I don't think they'd want people who downloaded the free game to have permanent ownership. In the case where the game temporarily goes on sale 100%, it makes more sense though. Having a limited time to claim something might make it get more attention even.

**Comment by ssokolow** [comment]
Generally, how that tends to work on other systems is some kind of mechanism to clone a new entry and rename the original to something like "(Classic)" or "(Beta)" or "(Free)" with the option to disable new purchases of it.

**Comment by Guard13007** [comment]
@leafo That's why I'd say make it optional to the developer. Something like a checkbox "allow users to claim ownership of this game".

**Comment by ssokolow** [comment]
@Guard13007  The problem with that is that it introduces complication in a system that's already struggling to be low-enough friction to make users care when they probably already have a games backlog.

**Comment by Guard13007** [comment]
Good point I didn't consider.

**Comment by Ragzouken** [comment]
Would just like to add that I have some things that I have deliberately avoided offering even pay-what-you-want because I didn't want anyone to think they were purchasing the program and all future updates  when I might actually make a paid version later

**Comment by ssokolow** [comment]
@Ragzouken 

...and the current solution runs counter to your interests because it uses the same UI styling for "buy" and "free download" buttons.

(Though, even then, it's natural to assume that you'll be getting all updates unless there's a name change like "[Name of Game] Plus". It's just human nature to assume that, once released for free, something will remain free, so you need to cue them with a name change. That's why you still see tons of copies of Grand Theft Auto 2 floating around the net despite Rockstar Classics no longer offering downloads.)

**Comment by leafo** [comment]
I've just deployed this for the [Gone Home sale](https://gonehome.itch.io/gonehome). It will be available for everyone shortly.

It works for promotions that are 100% off.

**Comment by Guard13007** [comment]
@leafo Is this available for everyone yet? And is it a toggle the developer has to enable or just part of the platform by default?

**Comment by leafo** [comment]
This is now available: https://twitter.com/itchdude/status/812855917725089792
