### ISSUE TITLE
Allow us to hide platforms

### ISSUE THREAD

**Issue by LiamDawe** [itchio/itch.io#564]
Something I would like to see, is the ability to only show games on itch on a specific platform, like Linux.

This would likely make itch more attractive to Linux gamers, and make things easier for me too.

It's something people request Steam do all the time, but maybe you could one-up them here.

I would also love to see such a feature (obviously).

**Comment by leafo** [comment]
You're referring to https://itch.io/games having the ability to show games that are linux exclusively?

**Comment by LiamDawe** [comment]
I mean the homepage, have a user defined setting that allows filtering the entire home-page to be Linux-only titles.

Like right now if I go to itch.io and want to find a new game to either play or write about, I have to hover over every single one to see if it supports Linux or not, it wastes quite a lot of time for me.

It also creates disappointment when I think "that looks fucking cool", I hover over and...Windows only, poop :(

**Comment by notnsane** [comment]
https://itch.io/games/platform-linux 

This isn't enough? While I understand your point, I think it's more important for itch.io to showcase _creations_ on _any_ platform on the front page.

**Comment by LiamDawe** [comment]
No it's not enough.

As someone who is around the community 24/7 when he's awake, I know all too well how important good filtering is. Do you know what the #1 complaint about Steam is from Linux gamers? Showing Windows games on the Steam homepage. Don't be Steam, be cool itch.

For Linux gamers, there's practically no reason to show games on other platforms, it's actually a barrier to Linux users seeing games they could buy right away, it's just cruft in the way.

If it's a toggle option in user settings rather than the default, it will cover all bases then.

**Comment by quyse** [comment]
I never understood that obsession about eliminating non-Linux games from store's front page. It's not hard to get a list of Linux-supported games on itch, it's just one click away, and I can always bookmark that page in my browser instead of front page. Although I'm a Linux fan, I don't feel any need in punishing non-Linux games by not showing them to me. A lot of games are playable with Wine. Some games may have their Linux version in-progress, but will be filtered out, so you won't even know about their existence if you hide them.

There's another thing. (Obviously) itch is mostly about indie games made by small teams with small budgets. So if I see a game not supporting Linux, I think that it might be that the author just doesn't know Linux, or doesn't have necessary porting skills, or doesn't have time to do a Linux port, or doesn't have money to hire someone to do Linux port. But it's still a creation deserving its place on the front page and worth knowing about. Simply ignoring such games and their authors is not constructive here, is it? Maybe offering help in Linux porting/testing or asking the author for Linux version and then pre-buying the game if they promise to port it would be more helpful than avoiding them.

So my feeling is that this feature doesn't worth its development cost, and probably even harmful.

**Comment by LiamDawe** [comment]
I wouldn't call it an obsession, it's a feature request. A rather simple one at that. I'm not even asking for it by default, but a simple per-user toggle to satisfy the needs of those that want it.

It's not punishment to not display a non-compatible game where the user isn't likely to buy it.

If it was really that harmful, why have filters for platforms at all? What if the only page we ever went to was a bookmarked list of the Linux games filter?

Is a Linux user more likely to buy from itch if the first thing they see is great Linux games available, or to have them sift through non-compatible games? Regardless of their being a page to filter per-platform, the whole idea of the homepage is to showcase good games, if the platform list was that good it would be the homepage.

**Comment by stqn1** [comment]
I totally agree with Liam. Make it an option so everybody’s happy. And remove the need to hover pictures to see crucial information… The home page is completely useless for linux users at the moment.

**Comment by Luke-Nukem** [comment]
There is nothing worse than having to hover over something to see what it supports. Either make that information visible by default, or give users the options required for setting up a default filter for the page that is seen first.

**Comment by timo** [comment]
with the filter for making "no linux support" items disappear, i don't see a reason to move platform support out of the hover info box. so i'd be :+1: on adding the filter, but leaving display of information the way it is right now

**Comment by fasterthanlime** [comment]
I don't see anything wrong with requesting this feature - as mentioned though, it might take some time to adjust all areas of the site to respect this setting - would an incremental approach be better than nothing? (first the front page, then other pages in time?)

**Comment by LiamDawe** [comment]
Any approach towards getting it ready would be most welcome :)

Maybe figure out how you will do it step by step (some small roadmap), that way we know what does and doesn't do it and keep track?

**Comment by fasterthanlime** [comment]
Hey I just noticed this, looks like @leafo deployed it a week ago :)

![filtering-all-to-linux](https://cloud.githubusercontent.com/assets/7998310/22506951/5992ce96-e883-11e6-974d-8e666ebc8285.png)

**Comment by LiamDawe** [comment]
Great stuff, can probably close this now then.
