### ISSUE TITLE
Authenticate player without manifest.

### ISSUE THREAD

**Issue by lvivtotoro** [itchio/itch.io#592]
Is it possible to use the serverside API to authenticate players?  
I don't see anything on the wiki page that helps me with this.

**Comment by fasterthanlime** [comment]
https://itch.io/docs/api/serverside contains a bunch of API endpoints you might be interested in.

However, [the app](https://itch.io/app) provides the best experience for players. Using the API directly  means you'll need to ask players to give you their e-mail - and then you can use `https://itch.io/api/1/KEY/game/GAME_ID/download_keys` to check if that e-mail has a key (but even then, what prevents them from just using someone else's e-mail? you'd have to send an e-mail to that address and have them click on some link you control, to make sure they have access to that address..)

The app flow is much easier:

  * Players have to be logged into the app to use it
  * The app passes along a game-specific API key to your game (as an environment variable), which is much harder to spoof - and you can authenticate them without any interaction on their part.

I really really recommend going along with the app - if you can't, I'm interested in the reasoning and how we can improve it so that it works for your usecase too!

**Comment by lvivtotoro** [comment]
How would I test my games without uploading the game for the app?

**Comment by fasterthanlime** [comment]
> How would I test my games without uploading the game for the app?

Currently you can't. It's a planned feature for later though!

With butler, only the initial upload should take some time - the next pushes should be quick, since it only uploads what's changed.

**Comment by lvivtotoro** [comment]
Okay thank you. One last question though.  
The [manifest wiki page](https://itch.io/docs/itch/integrating/manifest.html) says about a `scope` parameter, but it said what a parameter is. Is it something like this:

    [[action]]
    ...
    scope=profile:me

**Comment by fasterthanlime** [comment]
> Is it something like this:

Yep! I linked you to an example manifest file that does it right in the itch.io thread - here's the link again: https://github.com/fasterthanlime/sample-evil-app/blob/master/itch.toml

**Comment by lvivtotoro** [comment]
Okay, thank you!

**Comment by lvivtotoro** [comment]
Some problem I missed then is what happens next when you've got the key?
Do you send it to the server? That seems like bad practice since it would slow it down.

**Comment by Guard13007** [comment]
> I really really recommend going along with the app - if you can't, I'm interested in the reasoning and how we can improve it so that it works for your usecase too!

If the player doesn't want to use the app, I don't want to force them to, but I still want to authenticate them.

**Comment by fasterthanlime** [comment]
> Some problem I missed then is what happens next when you've got the key?
> Do you send it to the server? That seems like bad practice since it would slow it down.

@lvivtotoro Once you've got the key:

  * Send it to your server
  * Your server makes a request to the itch.io server to authenticate the player

You only need to do it once when the game starts - then, if you wanted, you could generate a session ID on your server, and reply with that.

Then your game would use that session ID every time it talks to your server.

Can you explain when the slow down would happen?

---

@Guard13007 if you want to start a more general discussion, please open a separate thread, thanks! 🌟 (App-less authentication is already possible, but it's inherently more complicated, which is why I recommend supporting the app first).

**Comment by lvivtotoro** [comment]
The server's supposed to be keeping the game on, isn't it?  
Making HTTP connections at the same time just seems strange to me

**Comment by fasterthanlime** [comment]
> The server's supposed to be keeping the game on, isn't it?
> Making HTTP connections at the same time just seems strange to me

HTTP is just one way for your server to talk to the itch.io and authenticate the player (once).

It could take a few hundred ms at the start of your game - but during that time you can load assets, etc. - it really doesn't have to slow down anything.

By "the server's supposed to be keeping the game on", are you referring to "always-on DRM" ? I really advise against it - but that's also implemented by having the game make requests to the server regularly (via HTTP or otherwise) to check that it's allowed to play at a given moment.

**Comment by lvivtotoro** [comment]
No, by that I meant it like hosting a website. It turns off when the computer does

**Comment by fasterthanlime** [comment]
> No, by that I meant it like hosting a website. It turns off when the computer does

No, your server should not run on your user's machine :)

There's:

  * The game, ran on your many users' machines
  * Your server, which you can run wherever you want (Amazon EC2, Google Cloud Platform, Linode)
  * The itch.io server

The game talks to your server, which talks to the itch.io server.

**Comment by lvivtotoro** [comment]
I didn't say it was the _users_ computer.

A server is hosted on some computer. But if that computer has to make HTTP connections with the Itch.io servers, wouldn't it slow the game down increase the delay between the client and server?

**Comment by fasterthanlime** [comment]
> A server is hosted on some computer. But if that computer has to make HTTP connections with the Itch.io servers, wouldn't it slow the game down and increase the delay between the client and server?

Ah, no, because you only do it once, when a player connects. Then you remember that this connection = this user. That's it.

We're also looking into https://github.com/itchio/itch.io/issues/570 so that you don't even have to make that request - but it would still "happen" on the users' computer, it would just be done by the app instead of your server :)

**Comment by lvivtotoro** [comment]
Aight, thanks!
