### ISSUE TITLE
File upload API endpoint

### ISSUE THREAD

**Issue by hayksaakian** [itchio/itch.io#60]
In my ideal world, I would have continuous deployment of my game to itch.io

If you had an API endpoint to publish / upload my game I could build a simple CI client.

**Comment by icbat** [comment]
:+1: Would love this =)

**Comment by technomancy** [comment]
Pushing releases out from a makefile using curl would really make my day.

**Comment by fasterthanlime** [comment]
Quick status update: the current plan is to get https://github.com/itchio/butler fully working by the end of the month.

It's an open-source command-line tool in go that communicates over SSH with wharf, an internal itch.io service (closed-source) that itself communicates with the itch.io API.

Together they talk a protocol similar to rsync, compressing the payload with brotli q1.

We need that for an internal project, but afterwards, we'll probably look into adding public API endpoints to do uploads automatically, so that it can be integrated with "game maker tools" a-la Renpy/Construct 2/Superpowers/etc.

Personally I just don't want people to go the trouble of integrating with a temporary API endpoint whereas they could just as easily drop a butler binary & add a line to their existing build scripts, and get incremental updates for free :)

**Comment by leafo** [comment]
We now have butler: https://itch.io/docs/butler/

**Comment by musjj** [comment]
There is butler now, but I personally find the tool way too opinionated and limited. Do we have now a public API endpoint for uploading files?
