### ISSUE TITLE
Updating firejail doesn't work, having a firejail in $PATH confuses ibrew

### ISSUE THREAD

**Issue by AnummaBrooke** [itchio/itch.io#610]
Itch for Linux, 23.2.1. Goal: to enable sandboxing in preferences successfully. Problem: Auto configuration fails, and manual configuration causes app not to launch. Details:

I checked sandboxing in prefs, launched a game, and configuration process (entering root password) failed to launch any games and was repeated on each game launch.

I manually chowned and chmod-ed, according to https://itch.io/docs/itch/using/sandbox/linux.html.

The command ` ls -lhA ~/.config/itch/bin/firejail ` returns:
-rwsrwxr-x 1 root root 303K Jun 20  2016 /home/brooke/.config/itch/bin/firejail

When attempting to launch itch app, launch fails and shows error:
> "There was a problem during setup: unarchiver failed: /home/brooke/.config/itch/bin/firejail.7z: 7-Zip firejail (309496 B)... Failed! (Opening file failed)Extraction to directory "/home/brooke/.config/itch/bin" failed (1 file failed.)"

Hitting refresh icon, I see that itch is looking for "dependency firejail 0.9.41. I had already had firejail 0.9.38 installed. I have now installed 0.9.44, with the same result.

Deleting ~/.config/itch directory, and re-configuring itch app without sandboxing, allows itch app to launch normally again. But my current status is as above: permissions for firejail as pasted above, and error message when trying to launch itch app.

Thank you!

**Comment by fasterthanlime** [comment]
Hey there! Thanks for the detailed report.

> Hitting refresh icon, I see that itch is looking for "dependency firejail 0.9.41. I had already had firejail 0.9.38 installed. I have now installed 0.9.44, with the same result.

Do you mean you installed firejail independently? The itch app install its own, so that shouldn't be necessary.

> "There was a problem during setup: unarchiver failed: /home/brooke/.config/itch/bin/firejail.7z: 7-Zip firejail (309496 B)... Failed! (Opening file failed)Extraction to directory "/home/brooke/.config/itch/bin" failed (1 file failed.)"

That makes me think unarchiver wasn't able to write to ~/.config/itch/bin/firejail - but it seems to work for other users! I'm puzzled. Which distro are you using ?

**Comment by fasterthanlime** [comment]
I think I know what's happening. Once chmodded, it might actually not be possible for itch to write to the firejail binary anymore (but we've never pushed an update for it, so we never found that out) - and it wants to upgrade it because 0.9.38 and 0.9.44 didn't match 0.9.41 (the version it was expecting) - it's trying to "upgrade" because you already have a firejail in your path.

That's a bug, I'll fix it. This does mean we'll need sudo to upgrade firjeail though!

**Comment by fasterthanlime** [comment]
Moved to https://github.com/itchio/itch/issues/1146

**Comment by AnummaBrooke** [comment]
(Thank you, fasterthanlime! Just so I know I've answered your initial questions, my distro is Ubuntu 16.04. And, I had upgraded firejail 0.9.38 to 0.9.44 in an attempt to respond to itch app's apparent effort to find 0.9.41; that is, I supposed that itch might need firejail 0.9.41 _or above_ installed. Thanks again!)
