### ISSUE TITLE
Database for each game

### ISSUE THREAD

**Issue by lvivtotoro** [itchio/itch.io#646]
TF2 (for an example), also known as the **Hat Simulator** let's people get items and use them _across servers._  
It does this by connecting to Valve servers and some internal stuff goes on.

I'm developing a similar game in which items will be dropped and could be used across servers.

Will this be possible in the future or will each game have to host it's own database server somewhere?  
If it does, then what would be the identifier for each account in the database and how would they be authed?

**Comment by fasterthanlime** [comment]
> Will this be possible in the future or will each game have to host it's own database server somewhere?

Although it's possible that we develop such an API in the future, for now you should be running your own server with your own database.

The identifier for each account would be the user's "id".

You can see your own profile at https://itch.io/api/1/me/me (if you're signed into itch.io with your account).

As for your player's account:

  * Include an `.itch.toml` file with your game with a "scope = profile:me" line, see [this docs page](https://itch.io/docs/itch/integrating/manifest.html#api-key--scoping) and [this example file](https://github.com/fasterthanlime/sample-evil-app/blob/master/itch.toml)
  * Retrieve the API key from the environment variable `ITCHIO_API_KEY`.
    * Here's how to do it in javascript: [example](https://github.com/fasterthanlime/sample-evil-app/blob/de4dedd62a771d1f382772835fdd692f75c654e4/app/renderer.js#L72-L94) - however, in that example, the game is making the request directly to the itch.io server. What you want instead is to send that key to your server, and have your server make the http request.
  * Once your server makes the request, it reply to your game with maybe a unique session ID (you could use an [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) so that it's quite hard to guess).
  * The game will use that session ID to talk with your server further
  * Your server is in charge of remembering which session ID corresponds to which API key & itch.io user id.
  * You can make your server expire session IDs after, for example, an hour, at which point the game should send its key again, to get another session ID - and resume execution normally.

Hopefully these help more than #592 :)

I don't know what technology you're using to make the game, otherwise I could give you more details for your particular language/framework !

**Comment by lvivtotoro** [comment]
LibGDX, but not sure what you could help me with ;)
Thanks

**Comment by fasterthanlime** [comment]
> LibGDX, but not sure what you could help me with :)

Well, I'd start by linking you to

  * How to get an environment variable in Java: http://docs.oracle.com/javase/7/docs/api/java/lang/System.html#getenv%28%29
  * How to make an Http request with libgdx: https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/Net.HttpRequest.html

:)
