### ISSUE TITLE
Embedded swfs do not appear under some (unknown?) conditions

### ISSUE THREAD

**Issue by droqen** [itchio/itch.io#687]
Under some conditions itch.io embedded swfs don't show up at all, putting the 'Support This Game' link right at the top of the page. I don't know what causes this for other users, but I can personally reproduce it by opening it in Chrome in Incognito Mode.

This is pretty misleading and confusing for users: https://droqen.itch.io/undermine/comments

It would be nice to at least have a failure message, so affected users aren't presented with a bare page and no recourse.

**Comment by fasterthanlime** [comment]
It looks like

  * As of [at least 3 months ago](https://www.reddit.com/r/chrome/comments/640si8/flash_wont_run_in_incognito_mode/), Chrome started making Flash "Ask" instead of "Allow" by default in incognito mode (and perhaps elsewhere - fresh chrome installs maybe?)
  * When that's the case, `swfobject` (which we use for injecting the flash object) doesn't add anything to the DOM.

We could add a placeholder div of the right size with a message "Game won't load?" and some instructions, what do you think @leafo  ?

**Comment by leafo** [comment]
Not sure why flash wouldn't be loading but I added a fixed size container for the game with a message "This project requires Adobe Flash to run". Hopefully that will clear up any confusion in the future.
