### ISSUE TITLE
Android Authentication

### ISSUE THREAD

**Issue by lvivtotoro** [itchio/itch.io#726]
I've read up on the app authentication method, but Android does not have an app.
Or should I use something like Google's Identity system?

**Comment by leafo** [comment]
Are you referring to our OAuth application support or something else?

**Comment by lvivtotoro** [comment]
No, I am referring to the app manifest file which allows for safe authentication serverside (by passing a token)

**Comment by leafo** [comment]
In that case you'll have to use the ouath support since there's no launcher to start your game with an API token. You can read more here: https://itch.io/docs/api/oauth

I don't think we have anyone using it for Android yet, so tell me if you run into any issues. You might have some trouble figuring out the callback URL. If you want to use a app protocol URL then tell us.

**Comment by lvivtotoro** [comment]
Okay, I'll look into it, thank you

**Comment by lvivtotoro** [comment]
https://itch.io/user/oauth seems to result in a 404 error

**Comment by leafo** [comment]
if you copy and paste the Login URL shown on your app's page does that work? If so, can you compare what you're generating to what's there.

**Comment by lvivtotoro** [comment]
What Login URL?

**Comment by lvivtotoro** [comment]
Ah, I left out the response token parameter.
Well that was a waste of time.
