### ISSUE TITLE
Unable to complete CAPTCHA when logging into app

### ISSUE THREAD

**Issue by badon** [itchio/itch.io#765]
You should NOT have CAPTCHA's in your PC desktop software. This is crazy. Plus, I can't pass them. Even when everything is right, it won't let me past it. Sometimes it doesn't display correctly, and then it's a bit harder to (not) pass it. Huge waste of time.
![itch io pc software captcha 2017-12-13-wed-00-53-42](https://user-images.githubusercontent.com/5954485/33929947-18b55974-dfa0-11e7-89e6-b1829bfce3cb.png)

**Comment by leafo** [comment]
Our desktop app uses our API, and our API can be attacked by attacks the same way our website can be, so sometimes you may get a captcha while attempting to log in.

Do you you have trouble completing recaptcha in general, or is there something about it in the app that prevents you from completing it?

**Comment by badon** [comment]
As you can see in the screenshot, the CAPTCHA isn't displayed properly. There were worse ones that I didn't catch in a screenshot, but you can see in the provided screenshot that the instruction for the CAPTCHA aren't visible. In one instance the "VERIFY" button was off-screen. I do a lot of bug testing, so I was able to figure out how to screw with it and get it to work, but you can't expect that kind of persistence from an ordinary user that isn't trying to break it and find bugs and/or workarounds.

**Comment by leafo** [comment]
Were you not able to scroll in the dialog that contained the captcha?

**Comment by badon** [comment]
Yes, scrolling works, but there's no scrollbars and no other hint that it's not totally broken. Once again, a bug hunter like myself will be able to find workarounds, but an ordinary user is more likely to give up before they discover them. Since you're serving CloudFlare's CAPTCHA, you have no control over what exactly they try to stuff in there. Also, I discovered recently that the CAPTCHA sometimes won't display at all if I'm not logged-in to Google. It will simply give this error message:

![google recaptcha refuses to work 2017-12-07-thu 2 censored](https://user-images.githubusercontent.com/5954485/33952643-4ef67814-dfe7-11e7-8b02-03ae9a84177e.png)

It would be wise to find another way to authenticate to your API without relying on CloudFlare and Google's reCAPTCHA.

**Comment by leafo** [comment]
It's unlikely we'll be removing google's captcha. You may have to find another alternate way to anonymize your traffic if you're getting blocked logging in. Captchas only show up during log in if we're receiving suspicious traffic from your connecting network, or we need to temporarily boost global security verification due to spammers hitting out site. Sadly the same networks used by people trying to be anonymous are also used by people trying to abuse websites. That's just the reality of things right now.

Cloudflare is not used on API authentication, it's only used on our static asset domains. Their security challenge is separate, and we don't control it. (As I mentioned in the other ticket, I've lowed their protection as much as I can, but if they decide your network can't be trusted then you'll have to find an alternate way to connect)

**Comment by leafo** [comment]
Another option I'm open to exploring is letting you provide a two factor authentication code up front when logging in, and that will let you bypass any catpcha. You would need to have TFA enabled on your account of course.

**Comment by badon** [comment]
IPv4 addresses have been exhausted for almost 20 years now, if I remember correctly. Ordinary users of all kinds will encounter these problems with increasing frequency because of the increasing use of shared IP addresses. Some mobile networks ALWAYS get flagged as suspicious, and as I'm sure you already know, mobile traffic is one of the fastest growing areas of internet users.

In any case, I'm not anonymizing my traffic (per se). Since you only deal with non-anonymous users with accounts, you don't need to throw your hands up in despair if some of their networks are being used for abuse. You're already having good ideas for eliminating or reducing your need to rely on brute-force whole-network blocking, and I encourage you continue on that line of thinking. There are many straightforward solutions that could work for you. 

The only reason this problem is the most common on the internet is because people put too much trust in CloudFlare and Google, so they don't bother to test them. Consequently, Google thinks nothing of sending your customers away, with no communication whatsoever. As long as you don't know, or you don't care, they can do whatever they want to you.

**Comment by badon** [comment]
A screenshot would be interesting.

**Comment by TheFuzzyRiolu** [comment]
![image](https://user-images.githubusercontent.com/31224503/39962699-47bae95e-5625-11e8-9227-b0ebd0982a7c.png)
There's a screenshot of the error. This is the full error as text:

```
TypeError: Cannot read property 'recaptchaResponse' of null
    at Object.<anonymous> (C:\Users\Michael\AppData\Local\itch\app-23.6.3\resources\app.asar\appsrc\reactors\login.ts:50:54)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Michael\AppData\Local\itch\app-23.6.3\resources\app.asar\app\reactors\login.js:4:58)
    at <anonymous>
```

Is there some way I can get past this? I want to test to see how itch handles downloading the current release of my game.

**Comment by fasterthanlime** [comment]
@TheFuzzyRiolu that particular error happens in v23 when you click "Log in" before the CAPTCHA is solved properly.

In v25 (currently in QA) this bug doesn't exist, because there's no "Log in" button in the CAPTCHA dialog - it automatically advances to the next step when it's solved.

We're aware ReCAPTCHA isn't great and are actively looking into alternatives. Leaving it wide open is not an option for us at the moment, unfortunately.

Note that logging with your username (rather than your e-mail) will trigger a CAPTCHA less often.

**Comment by TheFuzzyRiolu** [comment]
@badon See, I originally wanted to use Steam but there's the $100 first-time publishing fee. I can't afford that fee and likely won't ever be able to for a long time. I'm still in high school, and I don't have _any way_ of getting an income. Itch doesn't have any publishing fees at all, therefore it is actually financially feasible to release free (as in speech), open-source, and free (as in no charge) software to the platform. Because of the $100 publishing fee, for someone like me, Steam is not financially feasible for that.

@fasterthanlime Good to know. How long will it take for the new version to get out of QA and become public? I'm okay with reCAPTCHA being used mostly because it's the most accessible to me given my blindness. When it works, it works well. Especially when it sees you as a human - you just have to tick a box, not fill out a picture or audio puzzle. Itch just desperately needs that patch if not anything else.

**Comment by alisonatwork** [comment]
This is also happening to me, but in a different way. reCAPTCHA is blocked in China along with many other Google services, so any site that forces a reCAPTCHA to login effectively blocks itself from the Chinese market. Of course there are workarounds, but even as a technical user it's very frustrating.

**Comment by leafo** [comment]
Recaptcha is used a security measure to protect the average account. We have a lot of people who try to run bots with stolen account credentials trying to see if they can get access to itch.io account. The captcha will only appear if our system detects something suspicious about how someone is logging in. Those heuristics can never be 100% accurate, and they are also not shared publicly.

That said, you can disable the login captcha by:

* Enable [Two Factor Authentication](https://itch.io/docs/advanced/two-factor-authentication) on your account
* The app's recaptcha can be skipped if you've logged into itch.io on your browser. (check is done by comparing IP addresses)

Thanks

**Comment by DigDeep38** [comment]
Recaptcha wasnt shown when I wanted to register to GitHub, I checked solutions which GitHub provides, but nothing helped. Then I disabled tracking protection in Firefox, after that I could see Recaptcha image, and was able to register to GitHub. Firefox says that there is nothing blocked on the site when you click on padlock, but Recaptcha is.

**Comment by badon** [comment]
> * Enable [Two Factor Authentication](https://itch.io/docs/advanced/two-factor-authentication) on your account

I don't own a smartphone, and there's no reason to assume everyone does. You can do two-factor authentication without requiring people to take on the burden of smartphones. Use email. Use smoke signals. Use whatever is convenient for the user. Locking people out based on technological prejudices does not make business sense.

**Comment by badon** [comment]
> Recaptcha wasnt shown when I wanted to register to GitHub, I checked solutions which GitHub provides, but nothing helped. Then I disabled tracking protection in Firefox, after that I could see Recaptcha image, and was able to register to GitHub. Firefox says that there is nothing blocked on the site when you click on padlock, but Recaptcha is.

If this is an issue with GitHub, you need to raise the issue with GitHub. This page is for Itch.io.

**Comment by Jozxyqk6** [comment]
Note that 2fa does not prevent the problem on my system.

Please get out of the stone age and use 2fa verification via email instead of relying on obsolete tech that blocks legitimate users.
