### ISSUE TITLE
Cannot turn on Discussion Board

### ISSUE THREAD

**Issue by bswaldmann** [itchio/itch.io#807]
My game had a discussion board, and I recently tagged it as having adult content. As a result of this, it seems to have disabled the Discussion Board, and every time I try to turn it back on, I save the page, refresh, and it's still disabled.

Are adult games just not allowed to have community pages? Either way, is there any way I can get back all the content in those forums that I no longer seem to have access to?

**Comment by leafo** [comment]
Sorry for not responding sooner. This sounds like a bug, all project pages are allowed to have a discussion board. Is it possible to give me a link to the page to look at it? If it's private you can email it so support@itch.io

Thanks

**Comment by leafo** [comment]
I'm closing this because we don't have any further information.

There is a known bug, when editing a game page if you have a lot of stuff on the edit page (very large description combined with many files), then options on the bottom of the page may get truncated. Generally this is from people who have uploaded dozens of files without cleaning them up. If this matches your page then you might want to try cleaning out older files.
