### ISSUE TITLE
Recover purchases by email

### ISSUE THREAD

**Issue by ryandcoates** [itchio/itch.io#818]
I've tried to go through this process a few times over the last few weeks now that my game is in Steam, I needed a key to enter, however I've not once received the email from itch.io, checked spam folders also
Email matches the one in my profile

any known issues here?

**Comment by leafo** [comment]
Hello, 

Sorry about the issue. There are no known issues with our purchase recovery system. Are you sure you're providing the same exact email address you used to purchase with?

I recommend contacting support since they can discuss private account information like purchases there to help you find the purchase. (If you already have, tell me the subject so I can go find the thread and make sure we get back to you quickly)
