### ISSUE TITLE
Editor color (dark mode) is black text on dark background

### ISSUE THREAD

**Issue by TangentFoxy** [itchio/itch.io#827]
As you can see here (or maybe you can't):

![image](https://user-images.githubusercontent.com/15093567/39852562-0b19d0fa-53d2-11e8-8a9a-2033c7dddee6.png)

There is a bit of text formatted as code, that is showing as black text on the very-nearly-black page, which makes it impossible to read.

**Comment by Deozaan** [comment]
This is still an issue with text wrapped in `blockquote` tags as well.

**Comment by Archeia** [comment]
I would like to bump this up since I also have this problem!

In the community tab, I cannot find a setting in the theme editor or CSS (since I'm not very good at it) to change the Code and Quote formatting text color. It's a bit of a pain since I have to share code with my users as well and yeah...

![image](https://user-images.githubusercontent.com/6222499/69110108-99dcd900-0ab4-11ea-96e1-522543aa99fd.png)

**Comment by leafo** [comment]
Fixed for next deploy, sorry about the delay!
