### ISSUE TITLE
Electron has a well-known CPU usage bug on single-core Windows 7 / Windows Server 2012

### ISSUE THREAD

**Issue by badon** [itchio/itch.io#833]
This is why I can't play Itch.io games anymore on my low-spec PC. See screenshots.
![itch io uses more cpu than all others combined 2018-05-18-fri-16-56-49 5](https://user-images.githubusercontent.com/5954485/40263627-08531ad0-5aca-11e8-8283-96e6d84c0c1e.jpg)

**Comment by leafo** [comment]
if you have the itch.io homepage open in your browser do you experience similar performance issues?

**Comment by badon** [comment]
I tried it in Google Chrome, and as long as I don't hover over any of the games to play the little video snippets, my CPU usage https://itch.io/ is very low, typically under 20% with lots of other things in the background.  Doing downloads or viewing game pages in the itch.io app will take 100% CPU and make my PC useless until I give it a "below normal" CPU priority with Process Hacker. I'm not really able to play itch.io games anymore, and I didn't realize the severity of this issue until I made my comparison with all the other gaming platforms today.

Do you have any low-spec hardware to test on? If not, then maybe you can set up a virtual machine to see what happens. Here are the specs on the PC I tested with:

Samsung Q1UP from 2004, with Intel Core Solo 1.33 GHz CPU and 2 GB RAM, with Intel 945 Express GMA 950 video on 1280 x 1024 external display (1024 x 600 native display) with Windows 7.

**Comment by fasterthanlime** [comment]
@badon this is a known issue with electron:

  * https://github.com/itchio/itch.io/issues/497
  * https://discuss.atom.io/t/electron-cpu-performance-on-windows-server-2012-r2/34573/2
  * https://stackoverflow.com/questions/39648969/node-js-electron-applications-for-single-core-windows-7-machines-are-slow-on-fil

Many people have tried to find fixes for it in the past, to no avail.

Incidentally, one of the pages mentions setting "Below Normal" priority as a workaround :)

Since this has been reported twice, I've added it to a list of Known issues: https://github.com/itchio/itch-docs/commit/d3ca08cac8f4a0b8b8f902283d6f67836a678a75 (it'll show up in https://itch.io/docs/itch/ as soon as the CI build finishes).
