### ISSUE TITLE
Feature request: Mastodon link field for profile pages.

### ISSUE THREAD

**Issue by ryliejamesthomas** [itchio/itch.io#839]
Hi!

At the moment there are optional fields for website and Twitter links in our creator page profiles, and I think it'd be great if we could get a field for Mastodon links too :)

To be clear I'm talking about the profiles at _username.itch.io_, not the ones at _itch.io/profile/username_.

Link in case you're not awware: https://joinmastodon.org/

**Comment by samuelfine** [comment]
Bumping/seconding this, given the recent events that have occurred on Twitter and the absolute explosion in Mastodon usage.

Would it be scope creep to suggest general purpose "social" links instead of only providing Twitter? It would add complexity on the UX front—instead of the well-known Twitter icon, either a generic icon or some sort of customizable one would be needed instead—but I do believe decentralizing social links is worthy enough for consideration, at least!

**Comment by hlashbrooke** [comment]
Came here to post this issue but found it already exists, so giving this a +1. It would be great to either add Mastodon as an option for social links (and therefore have the `rel="me"` attribute included with it) or have a way to add any social links within you like.

**Comment by ryliejamesthomas** [comment]
Yeah agreed, being able to include the `rel` attribute would help a lot. I run a game-making instance, and for lots of people there itch is their main website, so being able to verify that connection would help a lot.

**Comment by dos1** [comment]
See also #1388

**Comment by fluffy-critter** [comment]
Right now I would definitely like to see this. I have removed my Twitter link from my profile and it'd be nice if I could actively promote the social media I actually use (namely Mastodon). I have a link in my bio but it'd be nice if it were given the same position as the Twitter link.

For that matter, it'd be great to just have any arbitrary number of top-level social links (within a reasonable limit I guess), rather than there being any specific "blessed" social networks.

**Comment by ryliejamesthomas** [comment]
Closing, because this now exists (doesn't work with all Fediverse software, but that's another issue): https://mastodon.gamedev.place/@itchio/113476698236056658

**Comment by dos1** [comment]
> doesn't work with all Fediverse software

It doesn't fully work with Mastodon either - it only works on instances where the handle domain matches the web domain. Rewriting the handle into profile URL should be done via WebFinger lookup.

(edit: already filled as #1677)
