### ISSUE TITLE
can't download or update on mac beta

### ISSUE THREAD

**Issue by TopshyK** [itchio/itch.io#864]
the application crashes each time i go to update a game  or try to download a new one.

**Comment by fasterthanlime** [comment]
I've just installed the latest beta from https://fasterthanlime.itch.io/install-kitch on a fresh macOS install and it seems to work fine for me:

![screen shot 2018-07-24 at 11 36 59 am](https://user-images.githubusercontent.com/7998310/43159116-b8d51200-8f81-11e8-815a-5b7330d7b277.png)

Can you download & install the app again, see if you're still experiencing that problem?

**Comment by TopshyK** [comment]
[itch.txt](https://github.com/itchio/itch.io/files/2224990/itch.txt)
 here you go.

and I'm on the most recent beta of Mojave.

**Comment by fasterthanlime** [comment]
Ahhh, the *macOS* beta, not the itch app beta, got it!

I'll take a look.

**Comment by fasterthanlime** [comment]
Also, if you try the above steps, can you **also** try them with *this* version:

  * https://broth.itch.ovh/butler/darwin-amd64-head/572910c4b467b63db876df8b7dfb10aaa441cc9d/butler-darwin-amd64.zip

(trying with both versions is useful)

**Comment by TopshyK** [comment]
ok tried with both now what?

**Comment by fasterthanlime** [comment]
> ok tried with both now what?
> should i send the test.json files that were generated?

If the issue was what I thought it was, you wouldn't have gotten that far (butler would've crashed or something).

I still have no idea what's wrong with itch v23 on macOS 10.14 mojave, what I do know is that:

  * itch v23 (stable, the one you're using) works fine under macOS 10.12
  * itch v25 (beta) works fine under macOS 10.12 *and* macOS 10.14

so for now I'd just recommend using the itch beta: https://fasterthanlime.itch.io/install-kitch

Keeping this bug in mind, I guess it's becoming more urgent to make the itch beta the stable version. Thanks for your report! ✨

**Comment by TopshyK** [comment]
just opened kitch and its working better than itch was. i'm re-downloading some games currently and it hasn't crashed.
 thanks for your assistance.

**Comment by fasterthanlime** [comment]
> would i need to re-download any of the games i have?

Unfortunately yes.

The way the beta is set up, it's a completely separate install - this is done on purpose so that if the beta breaks, your stable install doesn't break.

Seeing as the beta is less and less broken compared to the stable version though.. we're looking at releasing it as stable very soon :) Thanks for the feedback!

**Comment by TopshyK** [comment]
thank you for all your help, and you are welcome for the feedback.
