### ISSUE TITLE
500 file limit inside HTML5 zip files?

### ISSUE THREAD

**Issue by TerryCavanagh** [itchio/itch.io#870]
Hello! I was narrowly below the 500 item limit for zip files with my last Dicey Dungeons update, and I think it's possible I'll overtake it soon, especially if I start providing multiple versions in the same zip file. 

Just wondering if there are plans to raise this limit? I'm sure it must be a problem for lots of different people - for example, I believe big HTML5 RPGMaker projects can have thousands of tiny files in their zips...

**Comment by leafo** [comment]
The 500 file limit isn't a technical one, but a recommendation for developers. RPG maker games using thousands of files are generally better off providing a downloadable version of their game, since the user experience of having to load a game with that many requests is not ideal. We recommend developers creating HTML5 games to consider things that web developers do: minification, concatenation, compression, etc.

I've lifted the limit from your account (it's at 3k files)

**Comment by TerryCavanagh** [comment]
Fair enough!
