### ISSUE TITLE
Payment page information failure, but still charges the customer

### ISSUE THREAD

**Issue by js6450** [itchio/itch.io#915]
I just tried to purchase a game, and the payment popup window asked for my card information. It detected an error in my zipcode that I entered, but still went ahead and charged my card, without leading me to the "successful payments" page. (I never received any emails for download / anything like that with this transaction.)

Probably / maybe the customer shouldn't be charged until they see that the purchase actually when through and they can see that the game purchased is downloadable?

**Comment by leafo** [comment]
What you're probably seeing is called a "preauthorization charge" and it's how our credit card processor checks if the payment information is valid.

You can learn more about it here: https://support.stripe.com/questions/why-does-my-customer-see-an-extra-1-00-charge-on-their-statement

The charge on your account is actually a hold on those funds, and since the payment did not go through it will automatically be reversed within the next day or so.

As far as I know, there's no way for us to alter this functionality. Sorry for the confusion.
