### ISSUE TITLE
[Feature Request] Ability to sort entries in un-ranked jams by downloads/ratings.

### ISSUE THREAD

**Issue by asheraryam** [itchio/itch.io#938]
In ranked jams, you can sort entries by their rank, which makes it easier to discover which ones are more worthwhile to download.

However in un-ranked jams, there is no way to filter the entries in a useful way to know which ones are worth checking out.

Example: https://itch.io/jam/extra-credits-game-design-jam/entries

What I suggest is the ability to filter these entries at least by downloads/ratings/popular.

**Comment by leafo** [comment]
By default, when unranked jam ends, the entries page will show things ordered by their global itch.io popularity. That should approximately give you what you want. It's unlikely we will add a direct "sort by downloads" option because downloads aren't always the best metric to judge a game by, and we don't share states about individual projects publicly.

**Comment by asheraryam** [comment]
@leafo Thank you, I did not know that they are sorted by default. 

That is already good enough for me. <3
