### ISSUE TITLE
Coupon/Discount System

### ISSUE THREAD

**Issue by Chinafreak** [itchio/itch.io#99]
Hello,

I've a request! I want add a big Software in itch.io but there is coupon/discount system missing! The coupon/discount should be only one and more redeemable. If this exists in itch.io, I'll love to add my big Software to itch.io! :)

- Yan

**Comment by larsiusprime** [comment]
:+1: 

Coupons are extremely useful. They're not just another way to do discounts, either. They're a tried and true form of tracking where your sales are coming from -- send out a press release to website Y, include a coupon code. Run a demo on website X, include a coupon code. Send a review copy to a journalist or a youtuber, give each a unique coupon code to share with their audience if they feel like it. Then, you can look in your sales and see which codes are used. (This isn't to be confused with an affiliate system where the journalist/youtuber/whatever gets a cut, it's just a coupon for the reader/viewer).

This requires no intrusive cookie-based tracking, and although it's crude, is in some ways more accurate than directly measuring traffic, because most click tracking can only account for recent browsing history -- what page were you on right before you made the sale? (Unless it's relying on really deep and invasive persistent cookies). Even if the coupon codes get shared around, it still gives you an idea of the relative influence of each source.

Humble Store meets nearly all of my needs at the moment except for unique coupons. This feature would put you a notch above in my eyes, provided the rest of the service is just as good.

**Comment by charliesgames** [comment]
Yeah, this would be super cool.
Cheers
Charlie

**Comment by fasterthanlime** [comment]
And it's live! http://blog.itch.io/post/152254766714/coupon-codes-for-sales-bundles
